### ISSUE TITLE
无法恢复 PIP 前的窗口状态

### ISSUE THREAD

**Issue by nophDog** [verygoodlee/mpv-pip#2]
`mpv v0.38.0-713-g2848af56`

脚本很实用，但是配置好之后，通过快捷键 `C` 进入 PIP 模式，再次摁 `C`，却无法恢复至之前的窗口大小和位置。

https://github.com/user-attachments/assets/c786efd8-9652-41f6-b7c1-988620cc6897

如果有地方可以自行配置，麻烦告知哈

**Comment by verygoodlee** [comment]
恢复正常窗口的位置是固定居中的，
窗口大小是根据 [--autofilt](https://mpv.io/manual/master/#options-autofit) [--autofit-larger](https://mpv.io/manual/master/#options-autofit-larger) [--autofit-smaller](https://mpv.io/manual/master/#options-autofit-smaller) 这三个选项自动计算的，按道理来说是恢复到刚打开视频的那个大小。
你这个确实不正常，太大了，不知道出了什么bug，提供下mpv.conf看看。

**Comment by nophDog** [comment]
> mpv.conf

```
vf=lavfi="fps=60:round=down"

autofit
no-border
snap-window

geometry=80%

sub-font-size=30
sub-font="Microsoft YaHei UI"

osd-font="Sarasa Mono SC"

window-corners=round
```

另外我还在用 [tomasklaen/uosc](https://github.com/tomasklaen/uosc)，不知道有没有影响

**Comment by verygoodlee** [comment]
不推荐使用`geometry`设置窗口大小，没适配这种情况，
使用`geometry`设置初始窗口位置，`autofit`设置初始窗口大小。
试试这样写，应该可以解决窗口太大的问题。
```ini
autofit=80%x80%  # 窗口80%大小
geometry=50%:50% # 窗口位置居中
```
[geometry](https://mpv.io/manual/master/#options-geometry)的语法比较混乱，既可设置位置也可设置大小，
已经有 [--autofilt](https://mpv.io/manual/master/#options-autofit) [--autofit-larger](https://mpv.io/manual/master/#options-autofit-larger) [--autofit-smaller](https://mpv.io/manual/master/#options-autofit-smaller) 这三个选项设置大小了，不知道为啥要这样设计

**Comment by nophDog** [comment]
> ```ini
> autofit=80%x80%  # 窗口80%大小
> geometry=50%:50% # 窗口位置居中
> ```

感谢，解决了恢复后窗口太大的问题👍

**Comment by MiKoto-Railgun** [comment]
我在input.conf里用
`c      no-osd script-binding pip/toggle;set window-maximized no;set window-scale 1`
可以达成楼主所说的类似效果
不过恢复时的窗口尺寸=视频分辨率
如果在进入画中画模式之前有特别调过窗口尺寸的话会强制恢复成视频尺寸

`script-binding pip/toggle        切换画中画窗口`
`set window-maximized no        退出最大化窗口（可以试试删掉此命令）`
`set window-scale 1        设置窗口尺寸为1`
`no-osd          去除osd文字显示`
